[build]
builder = "nixpacks"

[deploy]
startCommand = "python main.py"
healthcheckPath = "/ping"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[env]
PORT = { default = "8000" }
